title: Advaith Menon John
description: Engineering • Robotics • Data Analysis

author:
  name: Advaith Menon John

url: "https://advaithmj.github.io"
baseurl: ""

# Theme
theme: minima

# Navigation
header_pages:
  - projects.md
  - blog.md
  - about.md

# Social links
minima:
  social_links:
    github: advaithmj
